sudo: false

notifications:
    email: false

branches:
    only:
        - master

language: python

os:
    - linux

matrix:
    include:
        - python: '3.4'
          env: GMT=5.4.1
        - python: '3.5'
          env: GMT=5.4.1
        - python: '3.6'
          env: GMT=5.4.1 COVERAGE=true

env:
    global:
        - COVERAGE=false
        - CONDA_PREFIX=/home/travis/miniconda3

before_install:
    - source ci/install-miniconda.sh
    - conda update --yes conda
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip -c conda-forge
    - conda install --yes --file requirements.txt -c conda-forge
    - if [ "$COVERAGE" == "true" ]; then pip install coveralls==0.5; fi
    - conda list

install:
    - python setup.py bdist_wheel
    - pip install dist/*

script:
    - if [ "$COVERAGE" == "true" ]; then make coverage; else make test; fi
    - make pep8

after_success:
    - if [ "$COVERAGE" == "true" ]; then coveralls; fi

deploy:
    provider: pypi
    distributions: "sdist bdist_wheel"
    skip_upload_docs: true
    user: "Leonardo.Uieda"
    password:
        secure: KyVpqvLNGp+IXjKmqQR4ll43dSDNdqcJnP+7PmPCVOt+bRfjb6WmK6iATD5x8Yij4skt7olsE2dGk6mBbSjhJaaSK6zYxGMpSRs14IOOeKdj61v+1TuAKYq2A4ZO74he6kJRrM3yzZNyeg2WGAjCApMli7VGBizC/kxzWlsfpnBgrywOXDaDCxBSVhVssWpdfuhyHHbJCExhDw52gzErPkmLVzZpLzMTU4WSVO/BWytexvK3adtMURH+SCAvjFeBCpos0HF58rPdlyxOmczAmWGyROcDZ+BfshJy7L3v96fRoOWmONgJsKOHQQCnc8CrijI9A+MQrgzr5vifv2twutZfQGXe/TlhnUrJz7me05TYDTp9Gdopm3jAR1M2KRehLNnYEtni7t+21H3BXQfNinW7hrYXEp/2GPijJLOVRpgX4usvvnGgHnFVpTep+dTSA5TpOf1EEix0+zc6/o/bEwLKYUsQGMLAkcL64gzfNC/dVSH4c4OFvJZ+t7vIDTuk50ISvuvyROTFzhox2qWMJcC8DBb/TziJw1bESJ6g5MRNE3M6cIoGdn5zQ771YZrWn/Ij3RCRGsJ8fTu0agHKtpCyiePgM9OwQTG91P5s+KzrX6J8JnQHFO02sacemCHBLd6HAmglxtssWPTrqAG04nhmHba3ujjiWAb95Q154qE=
    on:
        tags: true
        branch: master
        python: '3.6'
