sudo: false

notifications:
    email: false

# Only build pushes from the master branch. PRs are always built. The master
# build will also push the newly built docs to fatiando.org/dev
branches:
    only:
        - master

language: python

os:
    - linux

matrix:
    include:
        - python: '3.4'
          env: GMT=5.4.1
        - python: '3.5'
          env: GMT=5.4.1
        #- python: '3.6'
          #env: GMT=trunk
        - python: '3.6'
          env: GMT=5.4.1 COVERAGE=true

env:
    global:
        - COVERAGE=false
        - CONDA_PREFIX=/home/travis/miniconda3

before_install:
    # Get Miniconda from Continuum
    # Need to source the script to set the PATH variable in this environment
    # (not the scripts environment)
    - source ci/install-miniconda.sh
    # Create a conda env to install required libraries
    - conda update --yes conda
    #- conda create -n testenv --yes pip python=$PYTHON
    #- source activate testenv
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip -c conda-forge
    # Install dependencies
    - conda install --yes --file requirements.txt -c conda-forge
    - if [ "$COVERAGE" == "true" ]; then pip install coveralls==0.5; fi
    #- if [ "$GMT" == "trunk" ]; then conda install --yes --file requirements-gmt.txt -c conda-forge; fi
    # Install gmt from conda-forge or checkout and build trunk (place in conda
    # path)
    #- if [ "$GMT" == "trunk" ]; then ./ci/install-gmt-trunk.sh; else conda install --yes gmt=$GMT -c conda-forge; fi
    # Show installed pkg information for postmortem diagnostic
    - conda list

install:
    # Package and install
    - python setup.py bdist_wheel
    - pip install dist/*

script:
    # Run the test suite
    - if [ "$COVERAGE" == "true" ]; then make coverage; else make test; fi
    # Check code for PEP8 style
    - make pep8

after_success:
    - if [ "$COVERAGE" == "true" ]; then coveralls; fi

deploy:
    provider: pypi
    distributions: "sdist bdist_wheel"
    user: "Leonardo.Uieda"
    password:
        secure: "LQwtdLef4DtFg8WqlP4fZTomZOILtTBU6HQBjSaJk4Hy2QzeHVjVbCUPCSAZBVO2Qrz2TGrnnWoc5JxxRzxVf9MAdKrzMKWabsEmt14HnlaZt2nDF7lumLD9UO8Cwx3YyVBK6CvYJxdIlxWg3H3BvSnZ89A8SJl6G75/fwH2a3v8tOqt/5iFPc9SK6HTTCCTqKZNgIYqSH2OhK2bW9fjRSRSWQa+8wyNlKbTc958npB9pjrlHhxphnJhUQ1/orH2hJH0if74nxqQz/tfphkkeJfO1aPcwgiGR+VszdXM5/sz03RoGZKTRBQBqooAMz1X2c9O5uVhWXeXLX34dl9PvFMZtkXIdl2+zpH+3CUWrc8c/QyrX92fizxsHcmjpXeTWUhtE66A/sKTAR34gFUkVAEotrHzy0VuWlgjeLs6nAsp29/sqM8/Vfj+RgaAid+vgorZKDl8d+X23OHwwN94eVH1zPCM88Ag/PkhP3wqFMktpAbgPxiTVbEMTKV3s/K8Yb5I4Lh0AoeBZmW4LGSE9M60Ah/KxbqtecQq6td5gjquNH1+SpQ1/FYdfolf8xOghIWK+eo9+5xlC8WuYdgFwBER5c8A0yh3PJQIPvtPYIRCN5IJ8JgSuH+uKgOtEFFLK2nrlQSYz6Zk46ZxRAES4yzZxP4ciBuXwgZFrpFObFI="
    #on:
        #tags: true
        #branch: master
    server: https://testpypi.python.org/pypi
