name: gmtmodernize
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.6
    - docopt
    - tqdm
    - pytest
    - pytest-cov
    - flake8
    - pylint
    - coverage
    # GMT dependencies
    - cmake
    - fftw
    - gdal
    - ghostscript
    - libnetcdf
    - hdf5
    - zlib
